import { z } from "zod";

export const ClinicalAssessmentSchema = z.object({
  caseSummary:z.string().min(1), triageLevel:z.enum(["routine","priority","urgent","emergency"]), redFlags:z.array(z.string()), abnormalObservations:z.array(z.string()), imagingObservations:z.array(z.string()), differentialConsiderations:z.array(z.string()), suggestedNextSteps:z.array(z.string()), questionsForClinician:z.array(z.string()), limitations:z.array(z.string()), requiresHumanReview:z.literal(true),
});
export type ClinicalAssessment=z.infer<typeof ClinicalAssessmentSchema>;
export type MinimalClinicalContext={complaint:string;symptomSummary:string;vitals:Record<string,string>;labs?:Array<{name:string;value:string;unit:string}>};
export interface ClinicalAnalysisProvider { readonly id:string; analyze(context:MinimalClinicalContext,requestId:string):Promise<ClinicalAssessment> }
export const CLINICAL_SYSTEM_PROMPT=`You provide preliminary clinician decision support only. Never act as a physician or claim certainty without evidence. Separate measured facts from interpretation, preserve units, name missing information, highlight urgent observations, never fabricate lab values, never claim to inspect an absent image, and never claim specialist approval. Use concise clinician-facing language. Human review is always required.`;
export function minimizeForAi(input:{fullName?:string;phone?:string;nationalId?:string}&MinimalClinicalContext):MinimalClinicalContext { return {complaint:input.complaint,symptomSummary:input.symptomSummary,vitals:input.vitals,labs:input.labs}; }
export class DemoClinicalAnalysisProvider implements ClinicalAnalysisProvider { readonly id="demo-clinical-v1"; async analyze(context:MinimalClinicalContext):Promise<ClinicalAssessment>{ const oxygen=Number.parseFloat(context.vitals.spo2??"100"); const urgent=oxygen<92; return ClinicalAssessmentSchema.parse({caseSummary:`DEMO/SYNTHETIC: ${context.complaint}`,triageLevel:urgent?"urgent":"priority",redFlags:urgent?[`SpO₂ ${context.vitals.spo2}%`]:[],abnormalObservations:urgent?["Past oxygen saturation"]:[],imagingObservations:["Tasvir taqdim etilmagan"],differentialConsiderations:["Klinik differensialni shifokor belgilashi kerak"],suggestedNextSteps:[urgent?"Shoshilinch klinik baholash":"Rejalashtirilgan klinik ko'rib chiqish"],questionsForClinician:["Qo'shimcha anamnez va tekshiruv natijalari bormi?"],limitations:["Deterministik demo provayder; tashxis emas"],requiresHumanReview:true}); } }
