export type DemoCase={code:string;name:string;age:number;sex:"Ayol"|"Erkak";region:string;village:string;clinic:string;complaint:string;triage:"emergency"|"urgent"|"priority"|"routine";reason:string;status:string;diagnostics:string[];submitted:string;aiSummary:string;clinicianFinal?:string;syncStatus:"synced"|"pending_sync"};
export const DEMO_CASES:DemoCase[]=[
{code:"QM-2027-0042",name:"Dilnoza Karimova",age:67,sex:"Ayol",region:"Samarqand",village:"G'us",clinic:"QishloqMed-01",complaint:"Nafas qisishi va ko'krakda bosim",triage:"emergency",reason:"SpO₂ 89%, taxikardiya va ko'krak bosimi",status:"Awaiting review",diagnostics:["Vitals","CBC","X-ray"],submitted:"8 min",aiSummary:"Synthetic demonstration. Not for clinical use. Multiple cardiopulmonary red flags require immediate physician verification.",syncStatus:"synced"},
{code:"QM-2027-0039",name:"Anvar Rahimov",age:42,sex:"Erkak",region:"Samarqand",village:"Chelak",clinic:"QishloqMed-01",complaint:"Isitma va yo'tal",triage:"urgent",reason:"38.7 °C, abnormal respiratory rate",status:"Awaiting review",diagnostics:["Vitals","X-ray"],submitted:"23 min",aiSummary:"Synthetic demonstration. Not for clinical use. Preliminary respiratory observations need physician verification.",syncStatus:"synced"},
{code:"QM-2027-0035",name:"Malika Usmonova",age:29,sex:"Ayol",region:"Samarqand",village:"Sazag'on",clinic:"QishloqMed-01",complaint:"Doimiy bosh og'rig'i",triage:"priority",reason:"Persistent symptoms and elevated BP",status:"More information requested",diagnostics:["Vitals"],submitted:"41 min",aiSummary:"Synthetic demonstration. Not for clinical use. Missing neurological examination limits assessment.",syncStatus:"synced"},
{code:"QM-2027-0031",name:"Rustam Norov",age:58,sex:"Erkak",region:"Jizzax",village:"Baxmal",clinic:"QishloqMed-01",complaint:"Holsizlik",triage:"priority",reason:"Abnormal hemoglobin reference comparison",status:"Awaiting review",diagnostics:["Vitals","CBC"],submitted:"1 h",aiSummary:"Synthetic demonstration. Not for clinical use. Laboratory abnormality requires clinician interpretation.",syncStatus:"synced"},
{code:"QM-2027-0028",name:"Saida Oripova",age:35,sex:"Ayol",region:"Samarqand",village:"Jomboy",clinic:"QishloqMed-01",complaint:"Routine examination",triage:"routine",reason:"No urgent observations",status:"Reviewed",diagnostics:["Vitals"],submitted:"2 h",aiSummary:"Synthetic demonstration. Not for clinical use. No urgent observations in provided data.",clinicianFinal:"Routine follow-up; return if symptoms develop.",syncStatus:"synced"},
{code:"QM-2027-0024",name:"Kamoliddin Aliyev",age:51,sex:"Erkak",region:"Jizzax",village:"Zomin",clinic:"QishloqMed-01",complaint:"Ko'krak og'rig'i",triage:"urgent",reason:"Combined symptom and BP findings",status:"Reviewed with edits",diagnostics:["Vitals","ECG"],submitted:"3 h",aiSummary:"Synthetic demonstration. Not for clinical use. Urgent review suggested.",clinicianFinal:"Urgent same-day cardiology referral after evidence review.",syncStatus:"synced"},
{code:"QM-2027-0021",name:"Feruza Xasanova",age:46,sex:"Ayol",region:"Samarqand",village:"Urgut",clinic:"QishloqMed-01",complaint:"Yo'tal",triage:"routine",reason:"Stable vital signs",status:"Offline draft",diagnostics:["Vitals"],submitted:"local",aiSummary:"AI not requested while offline.",syncStatus:"pending_sync"},
{code:"QM-2027-0017",name:"Temur Sobirov",age:63,sex:"Erkak",region:"Samarqand",village:"Oqdaryo",clinic:"QishloqMed-01",complaint:"Follow-up",triage:"priority",reason:"Previously reviewed abnormal observation",status:"Referral completed",diagnostics:["Vitals","Lab report"],submitted:"1 d",aiSummary:"Synthetic demonstration. Not for clinical use.",clinicianFinal:"Internal Medicine follow-up completed.",syncStatus:"synced"},
];
export const triageRank={emergency:0,urgent:1,priority:2,routine:3} as const;
export function sortByTriage<T extends {triage:keyof typeof triageRank}>(items:T[]){return[...items].sort((a,b)=>triageRank[a.triage]-triageRank[b.triage])}
