"use client";
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/human-body.glb --types --transform -o components/anatomy/HumanBodyModel.tsx 
Files: public/models/human-body.glb [1.58MB] > C:\Users\Umar\QishloqMedAI\components\anatomy\human-body-transformed.glb [68.5KB] (96%)
Author: Alexander Antipov (https://sketchfab.com/Dessen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/male-body-15a422001834483c9750ce6117d59cc1
Title: Male Body
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFAction = Record<string, unknown>;

type GLTFResult = GLTF & {
  nodes: {
    Low_Poly_Male_bodyGroup2_lambert1_0: THREE.Mesh;
  };
  materials: {
    lambert1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: React.ComponentPropsWithoutRef<'group'> & Record<string, unknown>) {
  const { nodes, materials } = useGLTF('/models/human-body-transformed.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Low_Poly_Male_bodyGroup2_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  );
}

useGLTF.preload('/models/human-body-transformed.glb');
