"use client";
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/human-body.glb --types --transform -o components/anatomy/HumanBodyModel.tsx 
Files: public/models/human-body.glb [25.39MB] > C:\Users\Umar\QishloqMedAI\components\anatomy\human-body-transformed.glb [1.13MB] (96%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFAction = Record<string, unknown>;

type GLTFResult = GLTF & {
  nodes: {
    Group16371: THREE.Mesh;
  };
  materials: {
    ['default']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: React.ComponentPropsWithoutRef<'group'> & Record<string, unknown>) {
  const { nodes, materials } = useGLTF('/models/human-body-transformed.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Group16371.geometry} material={materials['default']} />
    </group>
  );
}

useGLTF.preload('/models/human-body-transformed.glb');
